jwt:
  secret-key: ${JWT_SECRET_KEY:}
  rt-secret-key: ${JWT_RT_SECRET_KEY}
  validity-in-milliseconds: ${JWT_VALIDITY_MS}
  rt-validity-in-milliseconds: ${JWT_RT_VALIDITY_MS}
  temp-validity-in-milliseconds: ${JWT_TEMP_VALIDITY_MS}

spring:
  application:
    name: ecommerce
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
server:
  port: 8080