name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis: # Redis 서비스 추가
        image: redis
        ports:
          - 6379:6379

    steps:
      # 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 환경 변수 설정 (SPRING_PROFILES_ACTIVE 설정)
      - name: Set Spring profile
        run: echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV

      # Gradle 캐시 사용 설정 (빌드 속도 최적화)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 빌드 실행
      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon --stacktrace

      # 테스트 실행
      - name: Run tests
        run: ./gradlew test --no-daemon --stacktrace

      # 파일 디버깅
      - name: Debug file structure
        run: ls -R src/test/resources
